before:
  hooks:
    - go mod tidy
builds:
  - id: epithet-agent
    binary: epithet-agent
    main: ./cmd/epithet-agent/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - id: epithet-auth
    binary: epithet-auth
    main: ./cmd/epithet-auth/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - id: epithet-ca
    binary: epithet-ca
    main: ./cmd/epithet-ca/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: epithet
    tap:
      owner: epithet-ssh
      name: homebrew-epithet
    commit_author:
      name: Epithet Bot
      email: bot@epithet.io
    folder: Formula
    caveats: "Installs the binaries, but no configs"
    homepage: "https://epithet.io/"
    test: |
      system "#{bin}/epithet-agent --version"
