package main

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// profileTag returns the ssh Tag token for a profile. The default profile
// gets the bare "epithet" tag for ergonomics; named profiles get
// "epithet-<name>". Match tagged does exact-string matching, so the bare tag
// cannot collide with any suffixed one.
func profileTag(name string) string {
	if name == "default" {
		return "epithet"
	}
	return "epithet-" + name
}

// generateSSHConfig writes an SSH config file for this profile. A plain tagged
// block selects IdentityAgent as soon as the tag is available, whether the tag
// matched the original host on the first pass or the canonical host on the
// final pass. The broker call is separately gated by "Match final tagged
// epithet-<name>" so it sees the effective hostname after OpenSSH has performed
// any canonicalization. "final" also requests a second pass when
// canonicalization is disabled, so epithet match runs at the same point for
// every connection. IdentityAgent expands %C when it is used, after
// canonicalization, so it addresses the same connection hash as the broker.
func (a *AgentCLI) generateSSHConfig(path, agentDir, brokerSock, homeDir string) error {
	// Find epithet binary path
	epithetPath, err := os.Executable()
	if err != nil {
		epithetPath = "epithet" // fallback to PATH
	}

	// Full home directory in the include pattern since ssh_config doesn't expand ~.
	includePattern := filepath.Join(homeDir, ".epithet", "run", "*", "ssh-config.conf")
	tag := profileTag(a.Name)

	// We only set IdentityAgent to point to the per-connection agent. This allows normal
	// fallback to ~/.ssh/id_* keys and password auth if epithet certificates aren't available,
	// which is important for production failure recovery.
	config := fmt.Sprintf(`# Generated by epithet agent - do not edit manually
# Profile: %s
#
# In ~/.ssh/config, tag the hosts this profile should handle, then include
# epithet's generated config AFTER the Tag lines (tags must be set before
# Match tagged is evaluated):
#
#   Host *.example.com
#       Tag %s
#   Include %s
#
# Requires OpenSSH 9.4 or newer (Tag / Match tagged).

Match tagged %s
    IdentityAgent %s/%%C

Match final tagged %s exec "%s match --host '%%h' --port '%%p' --user '%%r' --jump '%%j' --hash '%%C' --broker-socket '%s'"
`,
		a.Name,
		tag,
		includePattern,
		tag,
		agentDir,
		tag,
		epithetPath,
		brokerSock,
	)

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Truncate-and-rewrite: the rundir is named for the profile and persists
	// across restarts, so each start must overwrite any config left by a
	// prior run rather than assuming the file doesn't exist yet.
	if err := os.WriteFile(path, []byte(config), 0600); err != nil {
		return fmt.Errorf("failed to write SSH config: %w", err)
	}

	return nil
}

// checkSSHConfigInclude checks if ~/.ssh/config contains the Include directive for epithet
func checkSSHConfigInclude(homeDir, includePattern, name string, logger *slog.Logger) error {
	sshConfigPath := filepath.Join(homeDir, ".ssh", "config")

	// Read SSH config file
	content, err := os.ReadFile(sshConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			logger.Debug("~/.ssh/config does not exist", "path", sshConfigPath)
			return fmt.Errorf("SSH config not found")
		}
		return fmt.Errorf("failed to read SSH config: %w", err)
	}

	// Walk line by line (case-insensitive, flexible whitespace), tracking the
	// first Tag line so we can warn if the epithet Include precedes it: ssh
	// evaluates "Match tagged" against whatever tags are already set, so an
	// Include line above every Tag line would never see the tag activated.
	firstTagLineNum := -1
	includeLineNum := -1
	lineNum := 0
	lines := strings.SplitSeq(string(content), "\n")
	for line := range lines {
		lineNum++
		trimmed := strings.TrimSpace(line)
		// Skip comments
		if strings.HasPrefix(trimmed, "#") {
			continue
		}
		lower := strings.ToLower(trimmed)
		if firstTagLineNum == -1 && strings.HasPrefix(lower, "tag ") {
			firstTagLineNum = lineNum
		}
		// Check for Include directive (case-insensitive)
		if strings.HasPrefix(lower, "include ") {
			// Extract the path after "Include"
			parts := strings.Fields(trimmed)
			if len(parts) >= 2 {
				includePath := parts[1]
				// Expand ~ if present
				if strings.HasPrefix(includePath, "~/") {
					includePath = filepath.Join(homeDir, includePath[2:])
				}
				// Check if it matches our pattern
				if includePath == includePattern && includeLineNum == -1 {
					includeLineNum = lineNum
				}
			}
		}
	}

	if includeLineNum == -1 {
		return fmt.Errorf("Include directive not found")
	}

	logger.Debug("found epithet Include directive in ~/.ssh/config")
	switch {
	case firstTagLineNum == -1:
		// The Include is present but the user never wrote a Tag line at all —
		// the single most likely real-world misconfiguration, and one that
		// otherwise fails completely silently (epithet just never activates).
		logger.Warn(fmt.Sprintf("no 'Tag %s' lines found in ~/.ssh/config — epithet will never activate; tag the Host blocks it should handle", profileTag(name)))
	case includeLineNum < firstTagLineNum:
		logger.Warn("Include must come after Tag lines or epithet will never activate")
	}
	return nil
}
