#!/bin/sh

# PROVIDE: epithet_server
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf to enable this service:
#
# epithet_server_enable (bool):   Set to NO by default.
#                                 Set it to YES to enable epithet server.
# epithet_server_config (path):   Path to config file.
#                                 Default: /usr/local/etc/epithet/server.yaml
# epithet_server_logfile (path):  Path to log file.
#                                 Default: /var/log/epithet_server.log
# epithet_server_runas (str):     User to run as.
#                                 Default: epithet

. /etc/rc.subr

name="epithet_server"
rcvar="epithet_server_enable"

load_rc_config $name

: ${epithet_server_enable:="NO"}
: ${epithet_server_config:="/usr/local/etc/epithet/server.yaml"}
: ${epithet_server_logfile:="/var/log/epithet_server.log"}
: ${epithet_server_runas:="epithet"}

pidfile="/var/run/${name}.pid"
procname="/usr/local/bin/epithet"
command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} -u ${epithet_server_runas} ${procname} --config ${epithet_server_config} --log-file ${epithet_server_logfile} server"

run_rc_command "$1"
