// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: brokerv1/broker.proto

package brokerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection represents the complete tuple of SSH connection parameters.
type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalHost     string                 `protobuf:"bytes,1,opt,name=local_host,json=localHost,proto3" json:"local_host,omitempty"`
	RemoteHost    string                 `protobuf:"bytes,2,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	RemoteUser    string                 `protobuf:"bytes,3,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ProxyJump     string                 `protobuf:"bytes,5,opt,name=proxy_jump,json=proxyJump,proto3" json:"proxy_jump,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_brokerv1_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{0}
}

func (x *Connection) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *Connection) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *Connection) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

func (x *Connection) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Connection) GetProxyJump() string {
	if x != nil {
		return x.ProxyJump
	}
	return ""
}

func (x *Connection) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *Connection            `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_brokerv1_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{1}
}

func (x *MatchRequest) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

// MatchEvent is streamed during Match - stderr chunks then final result.
type MatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MatchEvent_Stderr
	//	*MatchEvent_Result
	Event         isMatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEvent) Reset() {
	*x = MatchEvent{}
	mi := &file_brokerv1_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEvent) ProtoMessage() {}

func (x *MatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEvent.ProtoReflect.Descriptor instead.
func (*MatchEvent) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{2}
}

func (x *MatchEvent) GetEvent() isMatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MatchEvent) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *MatchEvent) GetResult() *MatchResult {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isMatchEvent_Event interface {
	isMatchEvent_Event()
}

type MatchEvent_Stderr struct {
	Stderr []byte `protobuf:"bytes,1,opt,name=stderr,proto3,oneof"` // Auth plugin stderr chunk
}

type MatchEvent_Result struct {
	Result *MatchResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // Final result (exactly one, last)
}

func (*MatchEvent_Stderr) isMatchEvent_Event() {}

func (*MatchEvent_Result) isMatchEvent_Event() {}

type MatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_brokerv1_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{3}
}

func (x *MatchResult) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *MatchResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_brokerv1_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{4}
}

type InspectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SocketPath        string                 `protobuf:"bytes,1,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	AgentSocketDir    string                 `protobuf:"bytes,2,opt,name=agent_socket_dir,json=agentSocketDir,proto3" json:"agent_socket_dir,omitempty"`
	DiscoveryPatterns []string               `protobuf:"bytes,3,rep,name=discovery_patterns,json=discoveryPatterns,proto3" json:"discovery_patterns,omitempty"`
	Agents            []*AgentInfo           `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`
	Certificates      []*CertInfo            `protobuf:"bytes,5,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_brokerv1_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{5}
}

func (x *InspectResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *InspectResponse) GetAgentSocketDir() string {
	if x != nil {
		return x.AgentSocketDir
	}
	return ""
}

func (x *InspectResponse) GetDiscoveryPatterns() []string {
	if x != nil {
		return x.DiscoveryPatterns
	}
	return nil
}

func (x *InspectResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *InspectResponse) GetCertificates() []*CertInfo {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SocketPath    string                 `protobuf:"bytes,2,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Certificate   string                 `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_brokerv1_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{6}
}

func (x *AgentInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AgentInfo) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *AgentInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AgentInfo) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

type CertInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   string                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	HostUsers     map[string]*StringList `protobuf:"bytes,2,rep,name=host_users,json=hostUsers,proto3" json:"host_users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertInfo) Reset() {
	*x = CertInfo{}
	mi := &file_brokerv1_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertInfo) ProtoMessage() {}

func (x *CertInfo) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertInfo.ProtoReflect.Descriptor instead.
func (*CertInfo) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{7}
}

func (x *CertInfo) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *CertInfo) GetHostUsers() map[string]*StringList {
	if x != nil {
		return x.HostUsers
	}
	return nil
}

func (x *CertInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// StringList is needed because protobuf map values cannot be repeated.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_brokerv1_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_brokerv1_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_brokerv1_broker_proto_rawDescGZIP(), []int{8}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_brokerv1_broker_proto protoreflect.FileDescriptor

const file_brokerv1_broker_proto_rawDesc = "" +
	"\n" +
	"\x15brokerv1/broker.proto\x12\x11epithet.broker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\n" +
	"Connection\x12\x1d\n" +
	"\n" +
	"local_host\x18\x01 \x01(\tR\tlocalHost\x12\x1f\n" +
	"\vremote_host\x18\x02 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_user\x18\x03 \x01(\tR\n" +
	"remoteUser\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"proxy_jump\x18\x05 \x01(\tR\tproxyJump\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\"M\n" +
	"\fMatchRequest\x12=\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x1d.epithet.broker.v1.ConnectionR\n" +
	"connection\"i\n" +
	"\n" +
	"MatchEvent\x12\x18\n" +
	"\x06stderr\x18\x01 \x01(\fH\x00R\x06stderr\x128\n" +
	"\x06result\x18\x02 \x01(\v2\x1e.epithet.broker.v1.MatchResultH\x00R\x06resultB\a\n" +
	"\x05event\"9\n" +
	"\vMatchResult\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x10\n" +
	"\x0eInspectRequest\"\x82\x02\n" +
	"\x0fInspectResponse\x12\x1f\n" +
	"\vsocket_path\x18\x01 \x01(\tR\n" +
	"socketPath\x12(\n" +
	"\x10agent_socket_dir\x18\x02 \x01(\tR\x0eagentSocketDir\x12-\n" +
	"\x12discovery_patterns\x18\x03 \x03(\tR\x11discoveryPatterns\x124\n" +
	"\x06agents\x18\x04 \x03(\v2\x1c.epithet.broker.v1.AgentInfoR\x06agents\x12?\n" +
	"\fcertificates\x18\x05 \x03(\v2\x1b.epithet.broker.v1.CertInfoR\fcertificates\"\x9d\x01\n" +
	"\tAgentInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1f\n" +
	"\vsocket_path\x18\x02 \x01(\tR\n" +
	"socketPath\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12 \n" +
	"\vcertificate\x18\x04 \x01(\tR\vcertificate\"\x8f\x02\n" +
	"\bCertInfo\x12 \n" +
	"\vcertificate\x18\x01 \x01(\tR\vcertificate\x12I\n" +
	"\n" +
	"host_users\x18\x02 \x03(\v2*.epithet.broker.v1.CertInfo.HostUsersEntryR\thostUsers\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a[\n" +
	"\x0eHostUsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.epithet.broker.v1.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\xac\x01\n" +
	"\rBrokerService\x12I\n" +
	"\x05Match\x12\x1f.epithet.broker.v1.MatchRequest\x1a\x1d.epithet.broker.v1.MatchEvent0\x01\x12P\n" +
	"\aInspect\x12!.epithet.broker.v1.InspectRequest\x1a\".epithet.broker.v1.InspectResponseB=Z;github.com/epithet-ssh/epithet/pkg/broker/brokerv1;brokerv1b\x06proto3"

var (
	file_brokerv1_broker_proto_rawDescOnce sync.Once
	file_brokerv1_broker_proto_rawDescData []byte
)

func file_brokerv1_broker_proto_rawDescGZIP() []byte {
	file_brokerv1_broker_proto_rawDescOnce.Do(func() {
		file_brokerv1_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brokerv1_broker_proto_rawDesc), len(file_brokerv1_broker_proto_rawDesc)))
	})
	return file_brokerv1_broker_proto_rawDescData
}

var file_brokerv1_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_brokerv1_broker_proto_goTypes = []any{
	(*Connection)(nil),            // 0: epithet.broker.v1.Connection
	(*MatchRequest)(nil),          // 1: epithet.broker.v1.MatchRequest
	(*MatchEvent)(nil),            // 2: epithet.broker.v1.MatchEvent
	(*MatchResult)(nil),           // 3: epithet.broker.v1.MatchResult
	(*InspectRequest)(nil),        // 4: epithet.broker.v1.InspectRequest
	(*InspectResponse)(nil),       // 5: epithet.broker.v1.InspectResponse
	(*AgentInfo)(nil),             // 6: epithet.broker.v1.AgentInfo
	(*CertInfo)(nil),              // 7: epithet.broker.v1.CertInfo
	(*StringList)(nil),            // 8: epithet.broker.v1.StringList
	nil,                           // 9: epithet.broker.v1.CertInfo.HostUsersEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_brokerv1_broker_proto_depIdxs = []int32{
	0,  // 0: epithet.broker.v1.MatchRequest.connection:type_name -> epithet.broker.v1.Connection
	3,  // 1: epithet.broker.v1.MatchEvent.result:type_name -> epithet.broker.v1.MatchResult
	6,  // 2: epithet.broker.v1.InspectResponse.agents:type_name -> epithet.broker.v1.AgentInfo
	7,  // 3: epithet.broker.v1.InspectResponse.certificates:type_name -> epithet.broker.v1.CertInfo
	10, // 4: epithet.broker.v1.AgentInfo.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 5: epithet.broker.v1.CertInfo.host_users:type_name -> epithet.broker.v1.CertInfo.HostUsersEntry
	10, // 6: epithet.broker.v1.CertInfo.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 7: epithet.broker.v1.CertInfo.HostUsersEntry.value:type_name -> epithet.broker.v1.StringList
	1,  // 8: epithet.broker.v1.BrokerService.Match:input_type -> epithet.broker.v1.MatchRequest
	4,  // 9: epithet.broker.v1.BrokerService.Inspect:input_type -> epithet.broker.v1.InspectRequest
	2,  // 10: epithet.broker.v1.BrokerService.Match:output_type -> epithet.broker.v1.MatchEvent
	5,  // 11: epithet.broker.v1.BrokerService.Inspect:output_type -> epithet.broker.v1.InspectResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_brokerv1_broker_proto_init() }
func file_brokerv1_broker_proto_init() {
	if File_brokerv1_broker_proto != nil {
		return
	}
	file_brokerv1_broker_proto_msgTypes[2].OneofWrappers = []any{
		(*MatchEvent_Stderr)(nil),
		(*MatchEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brokerv1_broker_proto_rawDesc), len(file_brokerv1_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brokerv1_broker_proto_goTypes,
		DependencyIndexes: file_brokerv1_broker_proto_depIdxs,
		MessageInfos:      file_brokerv1_broker_proto_msgTypes,
	}.Build()
	File_brokerv1_broker_proto = out.File
	file_brokerv1_broker_proto_goTypes = nil
	file_brokerv1_broker_proto_depIdxs = nil
}
